
services:
  fastapi:
    image: fast-api:312s
    build:
      context: .
    ports:
      - "8050:8050"
    volumes:
      - ./app:/app
    networks:
      - prep
    command: uvicorn main:app --host 0.0.0.0 --port 8050 --reload

networks:
  prep:
    driver: bridge